# Appveyor Build Scrip https://www.appveyor.com

version: 0.1.0.{build}

image: Visual Studio 2017

platform: Any CPU

configuration:
  - Debug
  - Release
  - WindowsDX Debug
  - WindowsDX Release
  #- Android Debug
  #- Android Release

install:
    - ps: src\.ci\windows\install.ps1

build:
  parallel: true
  project: src\Hero6.Windows.sln

test:
  assemblies:
    - '*.Tests.dll'
