# Travis-CI Build Script
#
# git-lfs isn't included to Travis image files so we have to install it ourselves and pull
# https://github.com/travis-ci/travis-ci/issues/3634
#
# MonoGame v3.5 doesn't work on Travis-CI, both on Linux and OS X because of a bug that breaks
# compability with older versions of unix like systems
# http://community.monogame.net/t/pipeline-tool-dllnotfoundexception/6852

language: csharp

notifications:
  email: false

os:
  - linux
  - osx

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      # git-lfs
      mkdir -p $HOME/bin;
      wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz;
      tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz;
      mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs;
      export PATH=$PATH:$HOME/bin/;

      # MonoGame
      wget http://www.monogame.net/releases/v3.4/MonoGame.Linux.zip;
      unzip ./MonoGame.Linux.zip;
    else
      # git-lfs
      brew update && brew install git-lfs;

      # MonoGame
      wget http://www.monogame.net/releases/v3.4/MonoGame.MacOS.pkg;
    fi;

  - find * -type f -exec chmod 777 {} \;

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      sudo ./generate.sh;
      yes y | sudo ./monogame-linux.run;
    else
      sudo installer -allowUntrusted -verboseR -pkg ./MonoGame.MacOS.pkg -target /;
    fi;

  - git lfs install

before_script:
  - git lfs pull

script:
  - cd src
  - ./build.sh
