# Travis-CI Build Script
# MonoGame v3.5 doesn't work on Travis-CI, both on Linux and OS X because of a bug that breaks
# compability with older versions of unix like systems
# http://community.monogame.net/t/pipeline-tool-dllnotfoundexception/6852

language: csharp

notifications:
  email: false

os:
  - linux
  - osx

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      wget http://www.monogame.net/releases/v3.4/MonoGame.Linux.zip;
      unzip ./MonoGame.Linux.zip;
    else
      wget http://www.monogame.net/releases/v3.4/MonoGame.MacOS.pkg;
    fi;

  - find * -type f -exec chmod 777 {} \;

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      sudo ./generate.sh;
      yes y | sudo ./monogame-linux.run;
    else
      sudo installer -allowUntrusted -verboseR -pkg ./MonoGame.MacOS.pkg -target /;
    fi;

script:
  - cd src
  - ./build.sh
