# Travis-CI Build Script
#
# git-lfs isn't included to Travis image files so we have to install it ourselves and pull
# https://github.com/travis-ci/travis-ci/issues/3634
#
# MonoGame v3.5 doesn't work on Travis-CI, both on Linux and OS X because of a bug that breaks
# compability with older versions of unix like systems
# http://community.monogame.net/t/pipeline-tool-dllnotfoundexception/6852

language: csharp

sudo: required

notifications:
  email: false

os:
  - linux
  - osx

before_install: ./src/.ci/before_install.${TRAVIS_OS_NAME}.sh

install: ./src/.ci/install.${TRAVIS_OS_NAME}.sh

before_script: ./src/.ci/before_script.${TRAVIS_OS_NAME}.sh

script: ./src/.ci/script.${TRAVIS_OS_NAME}.sh
