//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateStartStudio.Hero6.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LateStartStudio.Hero6.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t quite reach it..
        /// </summary>
        public static string AlbionSignGrab {
            get {
                return ResourceManager.GetString("AlbionSignGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This must be Albion..
        /// </summary>
        public static string AlbionSignLook {
            get {
                return ResourceManager.GetString("AlbionSignLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It talks as much as any other piece wood..
        /// </summary>
        public static string AlbionSignTalk {
            get {
                return ResourceManager.GetString("AlbionSignTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You remove the twisted sword from the ground and take it with you. Let&apos;s hope your own sword does not end the same shape..
        /// </summary>
        public static string BentSwordGrab {
            get {
                return ResourceManager.GetString("BentSwordGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like a sword..
        /// </summary>
        public static string BentSwordLook {
            get {
                return ResourceManager.GetString("BentSwordLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talking to swords are we?.
        /// </summary>
        public static string BentSwordTalk {
            get {
                return ResourceManager.GetString("BentSwordTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like a fountain..
        /// </summary>
        public static string FountainGrab {
            get {
                return ResourceManager.GetString("FountainGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like a fountain..
        /// </summary>
        public static string FountainLook {
            get {
                return ResourceManager.GetString("FountainLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaks like a fountain..
        /// </summary>
        public static string FountainTalk {
            get {
                return ResourceManager.GetString("FountainTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touching yourself isn&apos;t very hero-like..
        /// </summary>
        public static string HeroGrab {
            get {
                return ResourceManager.GetString("HeroGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just another Player Character..
        /// </summary>
        public static string HeroLook {
            get {
                return ResourceManager.GetString("HeroLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did the Hero or the pizza come first you wonder....
        /// </summary>
        public static string HeroTalk {
            get {
                return ResourceManager.GetString("HeroTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No! Bad Hero!.
        /// </summary>
        public static string LlewellaGrab {
            get {
                return ResourceManager.GetString("LlewellaGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a lady..
        /// </summary>
        public static string LlewellaLook {
            get {
                return ResourceManager.GetString("LlewellaLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You found my sword! Thank you so much!.
        /// </summary>
        public static string LlewellaTalk1 {
            get {
                return ResourceManager.GetString("LlewellaTalk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve lost my sword oh great hero!.
        /// </summary>
        public static string LlewellaTalk2 {
            get {
                return ResourceManager.GetString("LlewellaTalk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re my hero!.
        /// </summary>
        public static string LlewellaTalk3 {
            get {
                return ResourceManager.GetString("LlewellaTalk3", resourceCulture);
            }
        }
    }
}
