# Publish steps

# dotnet Publish
steps:
- task: DotNetCoreCLI@2
  displayName: Build Publish Files
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './src/Hero6.Desktop/Hero6.Desktop.csproj'
    zipAfterPublish: false
    arguments: '-c $(BuildConfiguration) -r $(Runtime)'
    nobuild: true

# Publish Hero6
- task: PublishBuildArtifacts@1
  displayName: Publish Hero6
  inputs:
    PathtoPublish: 'src/Hero6.Desktop/bin/Release/netcoreapp3.0/$(Runtime)/publish'
    ArtifactName: 'Hero6_$(Agent.OS)_$(Build.DefinitionName)_$(Build.BuildNumber)'
    publishLocation: 'Container'
