# Run Tests steps

steps:
# Run Tests
- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: 'test'
    projects: 'src/**/*.Tests.csproj'
    arguments: '-c $(BuildConfiguration)'
    nobuild: true

# Gather Coverage Reports
- bash: ./scripts/coverage.sh $(BuildConfiguration)
  displayName: Gather Coverage Reports

# Publish Coverage Reports
- task: PublishCodeCoverageResults@1
  displayName: Publish Coverage Reports
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'src/.coverage/cobertura/*.xml'
    failIfCoverageEmpty: true
